--RODZPARAM
INSERT INTO RodzajParametru VALUES (1,'Silnik', 'tak');
INSERT INTO RodzajParametru VALUES (2,'Skrzynia Biegów', 'tak');
INSERT INTO RodzajParametru VALUES (3,'Hamulce', 'tak');
INSERT INTO RodzajParametru VALUES (4,'Podwozie', 'tak');
INSERT INTO RodzajParametru VALUES (5,'Nadwozie', 'tak');
INSERT INTO RodzajParametru VALUES (6,'Pompa Wodna', 'tak');
INSERT INTO RodzajParametru VALUES (7,'Pompa Pianowa', 'nie');
INSERT INTO RodzajParametru VALUES (8,'Wysięgnik', 'nie');
INSERT INTO RodzajParametru VALUES (9,'Klimatyzacja', 'nie');
INSERT INTO RodzajParametru VALUES (10,'GPS', 'nie');
INSERT INTO RodzajParametru VALUES (11,'Zawieszenie', 'tak');

--PARAM
INSERT INTO Parametr VALUES (1,1,'Silnik Diesel 2.0', 'opis Mercedes Silnik Diesel 2.0', 5000, 'Mercedes', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (2,1,'Silnik Diesel 2.0', 'opis VOLVO Silnik Diesel 2.0', 4000,'VOLVO', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (3,1,'Silnik Diesel 2.0', 'opis M.A.N. Silnik Diesel 2.0', 6000,'M.A.N.', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (4,1,'Silnik Diesel 3.0', 'opis Mercedes Silnik Diesel 3.0', 7000, 'Mercedes', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (5,1,'Silnik Diesel 3.0', 'opis VOLVO Silnik Diesel 3.0', 6000,'VOLVO', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (6,1,'Silnik Diesel 3.0', 'opis M.A.N. Silnik Diesel 3.0', 8000,'M.A.N.', 'https://pin.it/kE3ks2d');

INSERT INTO Parametr VALUES (7,2,'Manualna Skrzynia Biegów', 'opis 7-dmio biegowa manualna skrzynia biegów', 5000, 'Mercedes', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (8,2,'Manualna Skrzynia Biegów', 'opis 7-dmio biegowa manualna skrzynia biegów', 5000, 'VOLVO', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (9,2,'Manualna Skrzynia Biegów', 'opis 7-dmio biegowa manualna skrzynia biegów', 5000, 'Eaton', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (10,2,'Automatyczna Skrzynia Biegów', 'opis skrzynia biegów samoczynnie zmieniająca
biegi w zależności od obciążenia silnika pojazdu, zwalniając użytkownika z konieczności ręcznej zmiany biegów. ', 8000,'VOLVO', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (11,2,'Automatyczna Skrzynia Biegów', 'opis skrzynia biegów samoczynnie zmieniająca
biegi w zależności od obciążenia silnika pojazdu, zwalniając użytkownika z konieczności ręcznej zmiany biegów. ', 7000,'Voith', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (12,2,'Automatyczna Skrzynia Biegów', 'opis skrzynia biegów samoczynnie zmieniająca
biegi w zależności od obciążenia silnika pojazdu, zwalniając użytkownika z konieczności ręcznej zmiany biegów. ', 9000,'ZF', 'https://pin.it/kE3ks2d');

INSERT INTO Parametr VALUES (13,3,'Hamulce hydrauliczne tarczowe ', 'opis hamulce hyfrauliczne o budowie tarczowej', 3000, 'TRW', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (14,3,'Hamulce hydrauliczne bębnowe', 'opis hamulce hyfrauliczne o budowie bębnowe', 4000, 'EATE', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (15,3,'Hamulce pneumatyczne tarczowe ', 'opis hamulce pneumatyczne o budowie tarczowej', 3500, 'Brembo', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (16,3,'Hamulce pneumatyczne bębnowe', 'opis hamulce pneumatyczne o budowie bębnowe', 4500, 'Textar', 'https://pin.it/kE3ks2d');

INSERT INTO Parametr VALUES (17,4,'Rama podluznicowa 4x2', 'opis podwozie pojazdu oparte na budowie podluznicowej w ukladzie 4x2', 4500, 'Mercedes', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (18,4,'Rama krzyżowa 6x4', 'opis podwozie pojazdu oparte na budowie krzyzowej w ukladzie 6x4', 4500, 'VOLVO', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (19,4,'Rama kratownicowa 4x4', 'opis podwozie pojazdu oparte na budowie kratownicowej w ukladzie 4x4', 4500, 'M.A.N.', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (20,4,'Rama centralna 6x6', 'opis podwozie pojazdu oparte na budowie centralnej w ukladzie 6x6', 4500, 'M.A.N.', 'https://pin.it/kE3ks2d');
INSERT INTO Parametr VALUES (21,4,'Rama plytowa 4x4', 'opis podwozie pojazdu oparte na budowie plytowej w ukladzie 4x4', 4500, 'VOLVO', 'https://pin.it/kE3ks2d');

--TypKonta
    INSERT INTO TypKonta Values  (1, 'Admin');
    INSERT INTO TypKonta Values  (2, 'Kierownik');
    INSERT INTO TypKonta Values  (3, 'Pracownik fizyczny');
    INSERT INTO TypKonta Values  (4, 'Dział handlowy');
    INSERT INTO TypKonta Values  (5, 'Serwisant');
    INSERT INTO TypKonta Values  (6, 'Kontrahent');
    INSERT INTO TypKonta Values  (7, 'Użytkownik');
--RodzajPojazdu
INSERT INTO rodzajPojazdu Values (1, 'lekki miejski wóz strażacki', 'Pojazd strażacki o wadze do 7.5 tony przeznaczony do poruszania się po drogach o utwardzonej nawierzchni');
INSERT INTO rodzajPojazdu Values (2, 'lekki uterenowiony wóz strażacki', 'Pojazd strażacki o wadze do 7.5 tony który może jeździć po drogach o twardej nawierzchni, ale też w ograniczonym zakresie poza nimi');
INSERT INTO rodzajPojazdu Values (3, 'lekki terenowy samochód pożarniczy', 'Pojazd strażacki o wadze do 7.5 tony zdolny do poruszania się po każdej drodze i bezdrożach');
INSERT INTO rodzajPojazdu Values (4, 'średni miejski wóz strażacki', 'Pojazd strażacki o wadze od 7.5 do 14 ton  przeznaczony do poruszania się po drogach o utwardzonej nawierzchni');
INSERT INTO rodzajPojazdu Values (5, 'średni uterenowiony wóz strażacki', 'Pojazd strażacki o wadze od 7.5 do 14 ton tony który może jeździć po drogach o twardej nawierzchni, ale też w ograniczonym zakresie poza nimi');
INSERT INTO rodzajPojazdu Values (6, 'średni terenowy samochód pożarniczy', 'Pojazd strażacki o wadze od 7.5 do 14 ton zdolny do poruszania się po każdej drodze i bezdrożach');
INSERT INTO rodzajPojazdu Values (7, 'ciężki miejski wóz strażacki', 'Pojazd strażacki o wadze powyżej 14 ton przeznaczony do poruszania się po drogach o utwardzonej nawierzchni');
INSERT INTO rodzajPojazdu Values (8, 'ciężki uterenowiony wóz strażacki', 'Pojazd strażacki o wadze powyżej 14 ton tony który może jeździć po drogach o twardej nawierzchni, ale też w ograniczonym zakresie poza nimi');
INSERT INTO rodzajPojazdu Values (9, 'ciężki terenowy samochód pożarniczy', 'Pojazd strażacki o wadze powyżej 14 ton zdolny do poruszania się po każdej drodze i bezdrożach');

--RodzajAwari
    INSERT INTO RodzajAwarii Values (RodzajAwariiID.nextVal, 'Pęknięta opona', 1);
    INSERT INTO RodzajAwarii Values (RodzajAwariiID.nextVal, 'Usterka sprzęgła', 1);
    INSERT INTO RodzajAwarii Values (RodzajAwariiID.nextVal, 'Awaria silnika', 1);
    INSERT INTO RodzajAwarii Values (RodzajAwariiID.nextVal, 'Awaria hamulców', 1);
    INSERT INTO RodzajAwarii Values (RodzajAwariiID.nextVal, 'Zapchany filtr DPF', 2);
    INSERT INTO RodzajAwarii Values (RodzajAwariiID.nextVal, 'Hałasujacy pasek', 2);
    INSERT INTO RodzajAwarii Values (RodzajAwariiID.nextVal, 'Stuki z zawieszenia', 2);
    INSERT INTO RodzajAwarii Values (RodzajAwariiID.nextVal, 'Pęknięta szyba przednia', 1);
    INSERT INTO RodzajAwarii Values (RodzajAwariiID.nextVal, 'Pęknięta szyba boczna', 3);
    INSERT INTO RodzajAwarii Values (RodzajAwariiID.nextVal, 'Dziurawy waż', 1);
    INSERT INTO RodzajAwarii Values (RodzajAwariiID.nextVal, 'Spalona żarówka', 3);
--Uzytkownik


INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Jan','Nowak','6','login1','haslo1');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Andrzej','Kowalski','3','login2','haslo2');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Piotr','Wiśniewski','3','login3','haslo3');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Krzysztof','Dąbrowski','6','login4','haslo4');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Stanisław','Lewandowski','3','login5','haslo5');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Tomasz','Wójcik','7','login6','haslo6');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Paweł','Kamiński','7','login7','haslo7');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Józef','Kowalczyk','3','login8','haslo8');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Marcin','Zieliński','3','login9','haslo9');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Marek','Szymański','3','login10','haslo10');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Michał','Woźniak','3','login11','haslo11');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Grzegorz','Kozłowski','3','login12','haslo12');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Jerzy','Jankowski','1','login13','haslo13');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Tadeusz','Wojciechowski','7','login14','haslo14');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Adam','Kwiatkowski','3','login15','haslo15');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Łukasz','Kaczmarek','3','login16','haslo16');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Zbigniew','Mazur','7','login17','haslo17');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Ryszard','Krawczyk','2','login18','haslo18');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Dariusz','Piotrowski','3','login19','haslo19');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Henryk','Grabowski','3','login20','haslo20');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Mariusz','Nowakowski','1','login21','haslo21');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Kazimierz','Pawłowski','3','login22','haslo22');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Wojciech','Michalski','6','login23','haslo23');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Robert','Nowicki','6','login24','haslo24');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Mateusz','Adamczyk','3','login25','haslo25');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Marian','Dudek','3','login26','haslo26');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Rafał','Zając','3','login27','haslo27');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Jacek','Wieczorek','6','login28','haslo28');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Janusz','Jabłoński','3','login29','haslo29');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Mirosław','Król','3','login30','haslo30');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Maciej','Majewski','3','login31','haslo31');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Sławomir','Olszewski','6','login32','haslo32');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Jarosław','Jaworski','1','login33','haslo33');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Kamil','Wróbel','1','login34','haslo34');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Wiesław','Malinowski','3','login35','haslo35');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Roman','Pawlak','2','login36','haslo36');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Władysław','Witkowski','7','login37','haslo37');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Jakub','Walczak','7','login38','haslo38');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Artur','Stępień','2','login39','haslo39');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Zdzisław','Górski','1','login40','haslo40');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Edward','Rutkowski','6','login41','haslo41');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Mieczysław','Michalak','1','login42','haslo42');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Damian','Sikora','3','login43','haslo43');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Dawid','Ostrowski','2','login44','haslo44');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Przemysław','Baran','7','login45','haslo45');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Sebastian','Duda','3','login46','haslo46');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Czesław','Szewczyk','3','login47','haslo47');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Leszek','Tomaszewski','2','login48','haslo48');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Daniel','Pietrzak','1','login49','haslo49');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Waldemar','Marciniak','3','login50','haslo50');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Anna','Wróblewski','3','login51','haslo51');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Maria','Zalewski','1','login52','haslo52');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Katarzyna','Jakubowski','6','login53','haslo53');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Małgorzata','Jasiński','3','login54','haslo54');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Agnieszka','Zawadzki','7','login55','haslo55');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Krystyna','Sadowski','2','login56','haslo56');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Barbara','Bąk','3','login57','haslo57');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Ewa','Chmielewski','6','login58','haslo58');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Elżbieta','Włodarczyk','3','login59','haslo59');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Zofia','Borkowski','7','login60','haslo60');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Janina','Czarnecki','3','login61','haslo61');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Teresa','Sawicki','7','login62','haslo62');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Joanna','Sokołowski','2','login63','haslo63');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Magdalena','Urbański','6','login64','haslo64');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Monika','Kubiak','3','login65','haslo65');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Jadwiga','Maciejewski','6','login66','haslo66');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Danuta','Szczepański','6','login67','haslo67');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Irena','Kucharski','7','login68','haslo68');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Halina','Wilk','7','login69','haslo69');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Helena','Kalinowski','3','login70','haslo70');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Beata','Lis','3','login71','haslo71');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Aleksandra','Mazurek','3','login72','haslo72');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Marta','Wysocki','3','login73','haslo73');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Dorota','Adamski','3','login74','haslo74');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Marianna','Kaźmierczak','2','login75','haslo75');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Grażyna','Wasilewski','3','login76','haslo76');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Jolanta','Sobczak','2','login77','haslo77');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Stanisława','Czerwiński','3','login78','haslo78');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Iwona','Andrzejewski','3','login79','haslo79');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Karolina','Cieślak','3','login80','haslo80');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Bożena','Głowacki','6','login81','haslo81');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Urszula','Zakrzewski','2','login82','haslo82');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Justyna','Kołodziej','1','login83','haslo83');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Renata','Sikorski','3','login84','haslo84');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Alicja','Krajewski','1','login85','haslo85');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Paulina','Gajewski','3','login86','haslo86');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Sylwia','Szymczak','3','login87','haslo87');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Natalia','Szulc','3','login88','haslo88');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Wanda','Baranowski','7','login89','haslo89');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Agata','Laskowski','1','login90','haslo90');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Aneta','Brzeziński','7','login91','haslo91');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Izabela','Makowski','2','login92','haslo92');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Ewelina','Ziółkowski','7','login93','haslo93');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Marzena','Przybylski','1','login94','haslo94');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Wiesława','Szymborska','1','login95','haslo95');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Genowefa','Moczydom','7','login96','haslo96');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Patrycja','Komisarz','2','login97','haslo97');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Kazimiera','Włodczyk','1','login98','haslo98');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Edyta','Kępka','2','login99','haslo99');
INSERT INTO Uzytkownik Values (uzytkownicyID.nextVal,'Stefania','Cedzyna','6','login100','haslo100');

--Pracownik

INSERT INTO Pracownik Values (pracownicyID.nextVal,'1',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'2',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'3',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'5',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'6',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'8',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'9',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'10',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'11',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'17',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'18',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'19',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'22',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'23',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'25',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'26',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'27',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'30',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'32',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'33',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'35',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'36',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'38',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'40',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'44',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'45',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'46',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'47',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'48',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'51',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'53',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'55',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'56',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'60',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'61',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'62',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'63',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'64',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'66',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'67',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'69',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'70',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'72',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'73',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'74',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'75',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'76',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'78',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'79',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'80',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'81',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'84',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'85',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'86',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'87',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'89',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'91',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'92',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'94',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'96',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'97',null,'Wolny');
INSERT INTO Pracownik Values (pracownicyID.nextVal,'98',null,'Wolny');
---
INSERT INTO Kontrahent Values (kontrahenciID.nextVal,'1','Państwowa Straż Pożarna');
INSERT INTO Kontrahent Values (kontrahenciID.nextVal,'4','Miasto Kielce');
INSERT INTO Kontrahent Values (kontrahenciID.nextVal,'23','Gmina Daleszyce');
INSERT INTO Kontrahent Values (kontrahenciID.nextVal,'24','Gmina Górno');
INSERT INTO Kontrahent Values (kontrahenciID.nextVal,'28','Narodowa Straż Leśna');
INSERT INTO Kontrahent Values (kontrahenciID.nextVal,'32','Koleje Państwowe');
INSERT INTO Kontrahent Values (kontrahenciID.nextVal,'41','Miasto Kraków');
INSERT INTO Kontrahent Values (kontrahenciID.nextVal,'53','Przedsiębiorstwo Energetyczne');
INSERT INTO Kontrahent Values (kontrahenciID.nextVal,'58','Państwowa Straż Pożarna');
INSERT INTO Kontrahent Values (kontrahenciID.nextVal,'64','Miasto Kielce');
INSERT INTO Kontrahent Values (kontrahenciID.nextVal,'66','Gmina Daleszyce');
INSERT INTO Kontrahent Values (kontrahenciID.nextVal,'67','Gmina Górno');
INSERT INTO Kontrahent Values (kontrahenciID.nextVal,'81','Narodowa Straż Leśna');
INSERT INTO Kontrahent Values (kontrahenciID.nextVal,'100','Koleje Państwowe');
---
INSERT INTO Zlecenie Values (ZlecenieID.nextVal,'1','2022-9-10','ul. Krakowska 12, 31-150 Kraków','w trakcie rozparzenia','25225','6');
INSERT INTO Zlecenie Values (ZlecenieID.nextVal,'4','2022-9-13','ul. Wrocławska 22, 50-001 Wrocław','w trakcie rozparzenia','19133','4');
INSERT INTO Zlecenie Values (ZlecenieID.nextVal,'2','2022-9-16','ul. Gdańska 32, 80-001 Gdańsk','w trakcie rozparzenia','19983','4');
INSERT INTO Zlecenie Values (ZlecenieID.nextVal,'3','2022-9-17','ul. Szczecińska 52, 70-001 Szczecin','w trakcie rozparzenia','22720','2');
INSERT INTO Zlecenie Values (ZlecenieID.nextVal,'8','2022-9-13','ul. Krakowska 12, 31-150 Kraków','w trakcie rozparzenia','11020','5');
INSERT INTO Zlecenie Values (ZlecenieID.nextVal,'2','2022-9-17','ul. Gdańska 32, 80-001 Gdańsk','w trakcie rozparzenia','21233','2');
INSERT INTO Zlecenie Values (ZlecenieID.nextVal,'1','2022-9-10','ul. Gdańska 32, 80-001 Gdańsk','w trakcie rozparzenia','18566','3');
INSERT INTO Zlecenie Values (ZlecenieID.nextVal,'3','2022-9-14','ul. Bydgoska 62, 85-001 Bydgoszcz','w trakcie rozparzenia','24354','6');
INSERT INTO Zlecenie Values (ZlecenieID.nextVal,'8','2022-9-11','ul. Wrocławska 22, 50-001 Wrocław','w trakcie rozparzenia','18710','5');
INSERT INTO Zlecenie Values (ZlecenieID.nextVal,'4','2022-9-17','ul. Krakowska 12, 31-150 Kraków','w trakcie rozparzenia','27782','5');
INSERT INTO Zlecenie Values (ZlecenieID.nextVal,'6','2022-9-11','ul. Poznańska 15, 60-001 Poznań','w trakcie rozparzenia','28769','7');
INSERT INTO Zlecenie Values (ZlecenieID.nextVal,'7','2022-9-12','ul. Wrocławska 22, 50-001 Wrocław','w trakcie rozparzenia','13455','1');
INSERT INTO Zlecenie Values (ZlecenieID.nextVal,'11','2022-9-10','ul. Lubelska 72, 20-001 Lublin','w trakcie rozparzenia','20434','4');
---
ALTER SESSION SET nls_date_format='yyyy-mm-dd';

